version: '3'
name: reward-closet-ai-api-server

services:
  nginx:
    container_name: nginx
    image: nginx:1.21.5-alpine
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - nginx-connection
  api-server:
    image: abjin/reward-closet-ai-api-server:latest
    container_name: api-server
    networks:
      - nginx-connection

networks:
  nginx-connection:
